<a href="https://colab.research.google.com/github/pooJa-verMa14/Machine-Learning/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Assignment-1
Based on NumPy**




In [2]:
import numpy as np  # linear algebra library used to handle matrices

Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 


In [3]:
arr = np.array([1,2,3,6,4,5]) #initializing the array
print(f"Initially array is --> {arr}")
print(f"After reversing array is --> {np.flip(arr) }")   #using flip fuction to reverse the elements

Initially array is --> [1 2 3 6 4 5]
After reversing array is --> [5 4 6 3 2 1]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods 


In [4]:
arr1 = np.array([[1,2,3],[2,4,5],[1,2,3]]) #initializing the array
print(f"Initially array is --> {arr1}")
print(f"After flatten array row wise is --> {arr1.flatten()}")  # it will flatten the array row wise
print(f"After flatten array column wise is --> {arr1.flatten('F')}")  # it will flatten the array column wise

Initially array is --> [[1 2 3]
 [2 4 5]
 [1 2 3]]
After flatten array row wise is --> [1 2 3 2 4 5 1 2 3]
After flatten array column wise is --> [1 2 1 2 4 2 3 5 3]


(c) Compare the following numpy arrays:

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[1, 2], [3, 4]])

In [5]:
arr1=np.array([[1,2],[3,4]]) 
arr2 = np.array([[1, 2], [3, 4]])
comparison = arr1 == arr2
equal_arrays = comparison.all()
print(equal_arrays)


True


(d) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [6]:
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(f"most frequent value in x is --> {np.bincount(x).argmax()} and its indexes are --> {np.where(x == np.bincount(x).argmax())}")
print(f"most frequent value in x is --> {np.bincount(y).argmax()} and its indexes are --> {np.where(x == np.bincount(y).argmax())}")


most frequent value in x is --> 1 and its indexes are --> (array([0, 5, 7, 8, 9]),)
most frequent value in x is --> 1 and its indexes are --> (array([0, 5, 7, 8, 9]),)


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find

i. Sum of all elements

ii. Sum of all elements row-wise

iii. Sum of all elements column-wise 


In [7]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(f"Sum of all elements in gfg --> {np.sum(gfg)}")
print(f"Sum of all elements row-wise in gfg --> {gfg.sum(axis=0)}")
print(f"Sum of all elements row-wise in gfg --> {gfg.sum(axis=1)}")

Sum of all elements in gfg --> 45
Sum of all elements row-wise in gfg --> [[20  9 16]]
Sum of all elements row-wise in gfg --> [[14]
 [16]
 [15]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

i. Sum of diagonal elements

ii. Eigen values of matrix

iii. Eigen vectors of matrix

iv. Inverse of matrix

v. Determinant of matrix 

In [25]:
 from numpy import linalg as LA
 n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
 print(f"Sum of diagonal elements in n_array --> {np.trace(n_array)}")
 w, v = LA.eig(n_array)
 print(f"Eigen values of matrix --> {w}")
 print(f"Eigen vectors of matrix \n {v}")
 print(f"Inverse of matrix \n {LA.inv(n_array)}")
 print(f"Determinant of matrix --> {LA.det(n_array)}")


Sum of diagonal elements in n_array --> 176
Eigen values of matrix --> [98.16835147 28.097044   49.73460452]
Eigen vectors of matrix 
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix 
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix --> 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy: 

i. p = [[1, 2], [2, 3]]

q = [[4, 5], [6, 7]]

ii. p = [[1, 2], [2, 3], [4, 5]]

q = [[4, 5, 1], [6, 7, 2]]


In [16]:
from numpy import cov
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
print(f"Multiplication of p and q \n {np.dot(p,q)} \n covariance between matirces \n {cov(p,q)}")

Multiplication of p and q 
 [[16 19]
 [26 31]] 
 covariance between matirces 
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [20]:
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
try :
  print(f"Multiplication of p and q \n {np.dot(p,q)} \n covariance between matirces \n {cov(p,q)}")
except:
  print("Multiplication not posssible (All the input array dimensions for the concatenation axis must match exactly)")

Multiplication not posssible (All the input array dimensions for the concatenation axis must match exactly)


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]);
 y = np.array([[1, 5, 0], [5, 10, 3]]),
  
find inner, outer and cartesian product?

In [24]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(f"Inner product of x and y \n {np.inner(x,y)}")
print(f"Outer product of x and y \n {np.outer(x,y)}")
print(f"Cartesian product of x and y \n {np.cross(x,y)}")  

Inner product of x and y 
 [[17 52]
 [13 62]]
Outer product of x and y 
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product of x and y 
 [[-20   4   7]
 [-84  36  20]]


Q2: Based on NumPy Mathematics and Statistics 


(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each 
row. 

iii. Mean, Median and Standard Deviation of flattened array, of each column, and 
each row

In [28]:
array = np.array([[1, -2, 3],[-4, 5, -6]])
print(f"Element-wise absolute value of array is \n {np.absolute(array)}")
print(f"25th percentile of flattened array : {np.percentile(arr, 25)}")
print(f"50th percentile of flattend array : {np.percentile(arr, 50)}")
print(f"75th percentile of flattend array : {np.percentile(arr, 70)}")
print(f"25th percentile for each column : {np.percentile(arr, 25, axis =0)}")
print(f"50th percentile for each column : {np.percentile(arr, 50, axis =0)}")
print(f"75th percentile for each column : {np.percentile(arr, 70, axis =0)}")
print(f"25th percentile for each row : {np.percentile(arr, 25, axis =1)}")
print(f"50th percentile for each row : {np.percentile(arr, 50, axis =1)}")
print(f"75th percentile for each row : {np.percentile(arr, 70, axis =1)}")


Element-wise absolute value of array is 
 [[1 2 3]
 [4 5 6]]
25th percentile of flattened array : 2.25
50th percentile of flattend array : 3.5
75th percentile of flattend array : 4.5
25th percentile for each column : 2.25
50th percentile for each column : 3.5
75th percentile for each column : 4.5


AxisError: ignored

(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling 
and truncated value, rounded values


In [29]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(f"Floor values : \n {np.floor(a)}")
print(f"Ceil values : \n {np.ceil(a)}")
print(f"Trucated values : \n {np.trunc(a)}")
print(f"Rounded values : \n {np.round(a)}")

Floor values : 
 [-2. -2. -1.  0.  1.  1.  3.]
Ceil values : 
 [-1. -1. -0.  1.  2.  2.  3.]
Trucated values : 
 [-1. -1. -0.  0.  1.  1.  3.]
Rounded values : 
 [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting 

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array 

ii. Indices of sorted array 

iii. 4 smallest elements 

iv. 5 largest elements 


In [32]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(f"Sorted array : \n {np.sort(array)}")
print(f"Indices of sorted array : \n {np.argsort(array)}")
arr1 = np.sort(array)
print(f"4 smallest elements : /n {arr1[:4]}")
print(f"5 largest elements : /n {arr1[-5:]}")

Sorted array : 
 [ 10  16  16  52  54  62 453]
Indices of sorted array : 
 [0 3 4 1 5 2 6]
4 smallest elements : /n [10 16 16 52]
5 largest elements : /n [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 

i. Integer elements only 

ii. Float elements only 


In [39]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

def isInt(num):
    return np.equal(np.mod(num, 1), 0)

for num in array:
    if isInt(num):
        print(num, "is an integer")


1.0 is an integer
2.0 is an integer
3.0 is an integer
2.0 is an integer


Q4: 
(a) Write a function named img_to_array(path) that reads an image from a specified path and 
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale 
images) 


In [43]:
!pip install Pillow
from PIL import Image

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [46]:
def img_to_array(path):
  image = Image.open(path)
  data = np.asarray(image)
  with open("file.txt","w") as file:
    file.write(f"{data}")

print("Greay scale image")
img_to_array('/content/sample_data/OIP.jpg')
print("RGB image")
img_to_array('/content/sample_data/OIP (1).jpg')

Greay scale image
RGB image


(b) Load the saved file into jupyter notebook?